"""create subscription levels

Revision ID: a87f6484fe28
Revises: 4fe3eeed9a9d
Create Date: 2025-02-17 10:18:50.975678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87f6484fe28'
down_revision = ''
branch_labels = None
depends_on = None


def upgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('subscription_required', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('subscription_level', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade(op):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_level')
    op.drop_column('challenges', 'subscription_required')
    # ### end Alembic commands ###
